name: snowflake_sales_aggregate_dbt
version: 1.0.0
config-version: 2

profile: snowflake_sales_aggregate_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  snowflake_sales_aggregate_dbt:
    marts:
      +materialized: table
      +tags: ["snowflake_sales_aggregate_dbt"]
