snowflake_sales_aggregate_dbt:          # must match name in dbt_project.yml
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "snowflake"
      user: "snowflake"
      password: "snowflake"
      role: ACCOUNTADMIN
      database: DEMO_DB
      warehouse: COMPUTE_WH
      schema: DEMO_SCHEMA